// Kategoriya spec ma'lumotlari — products.tsx dan ajratildi
// Barcha spec fields admin panel uchun

// ── Category config (for spec fields only) ────────────────────────────────────
export interface FieldDef { key: string; label: string; type: "text" | "number" | "select" | "toggle"; options?: string[]; unit?: string; placeholder?: string }

export const KORPUS_OPTS = ["LDSP Laminat","MDF","Eman massiv","Sosna massiv","Metall","Plastik","Kombinatsiya (LDSP+MDF)"];
export const FASAD_OPTS  = ["MDF bo'yalgan (emal)","Akril","Eman furnir","Matt laminat","PVC plyonka","Shisha (tempered)","Plastik ABS","Alyuminiy profil","Kombinatsiya"];

export interface CatSpec { names: string[]; emoji: string; fields: FieldDef[] }

export const CATEGORIES: CatSpec[] = [
  {
    names: ["Shkaflar", "Shkaflar va javonlar", "Javonlar"], emoji: "🚪",
    fields: [
      { key: "corpusMat",  label: "Korpus materiali (karkasi)",         type: "select", options: KORPUS_OPTS },
      { key: "facadeMat",  label: "Fasad materiali (ko'rinadigan yuz)", type: "select", options: FASAD_OPTS },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Oq, Wenge, Yong'oq" },
      { key: "width",      label: "Eni",                  type: "number",  unit: "sm",  placeholder: "150" },
      { key: "height",     label: "Balandligi",           type: "number",  unit: "sm",  placeholder: "200" },
      { key: "depth",      label: "Chuqurligi",           type: "number",  unit: "sm",  placeholder: "60" },
      { key: "doors",      label: "Eshiklar soni",        type: "select",  options: ["1","2","3","4","Kupe (slayder)","Akkordeon"] },
      { key: "drawers",    label: "Tortmachalar soni",    type: "select",  options: ["0","1","2","3","4","5+"] },
      { key: "mirror",     label: "Ko'zgu mavjud",        type: "toggle" },
      { key: "assembly",   label: "Yig'ilgan holda yetkazish", type: "toggle" },
    ],
  },
  {
    names: ["Oshxona mebellar", "Oshxonalar"], emoji: "🍳",
    fields: [
      { key: "corpusMat",  label: "Korpus materiali (karkasi)",           type: "select", options: KORPUS_OPTS },
      { key: "facadeMat",  label: "Fasad materiali (eshik va dekorlar)",  type: "select", options: ["MDF bo'yalgan (emal)","Akril","Plastik PVC","Eman furnir","Matt laminat","Shisha (tempered)","Alyuminiy profil"] },
      { key: "color",      label: "Asosiy rangi",         type: "text",    placeholder: "masalan: Oq, Kulrang, Yashil" },
      { key: "shape",      label: "Rejasi (shakli)",      type: "select",  options: ["To'g'ri (lineynyy)","L-shakl","U-shakl","P-shakl","Orolcha bilan"] },
      { key: "totalLen",   label: "Umumiy uzunlik",       type: "number",  unit: "sm",  placeholder: "300" },
      { key: "upperH",     label: "Yuqori shkaf balandligi", type: "number", unit: "sm", placeholder: "72" },
      { key: "countertop", label: "Ish yuzasi materiali", type: "select", options: ["LDSP","Granit","Sun'iy tosh","Eman massiv","Kompozit","Kvarts"] },
      { key: "sink",       label: "Lavabo bilan",         type: "toggle" },
      { key: "appliances", label: "Texnika kiritilgan",   type: "toggle" },
      { key: "hood",       label: "Degaz (vытяжка) bilan", type: "toggle" },
    ],
  },
  {
    names: ["Yotoq xonasi to'plam", "Yotoqona", "Yotoqxona"], emoji: "🛏️",
    fields: [
      { key: "corpusMat",  label: "Korpus materiali (karkasi)",         type: "select", options: KORPUS_OPTS },
      { key: "facadeMat",  label: "Fasad materiali (ko'rinadigan yuz)", type: "select", options: FASAD_OPTS },
      { key: "setType",    label: "Garnitur turi",        type: "select",  options: ["To'liq garnitur","Faqat karavot","Karavot + shkaf","Karavot + shkaf + komod"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Oq, Wenge, Marra" },
      { key: "bedSize",    label: "Karavot o'lchami",     type: "select",  options: ["90×200","160×220","180×220","170×210"] },
      { key: "headboard",  label: "Bosh to'ri turi",      type: "select",  options: ["Yumshoq to'r","Qattiq to'r","Kamarli","Yog'ochdan","Maxsus dizayn"] },
      { key: "storage",    label: "Qutilar bilan (yotoq ostida)", type: "toggle" },
      { key: "mattress",   label: "Matras bilan birga",   type: "toggle" },
      { key: "nightstand", label: "Tungi stol bilan",     type: "toggle" },
    ],
  },
  {
    names: ["Divan va kreslolar", "Divonlar", "Kreslo"], emoji: "🛋️",
    fields: [
      { key: "corpusMat",  label: "Korpus materiali (karkas)",          type: "select", options: ["Yog'och (qayın/eman)","Metall","Plastik tayanch","Kombinatsiya"] },
      { key: "facadeMat",  label: "Qoplama materiali",                  type: "select", options: ["Haqiqiy teri","Eko-teri","Mato (trikotaj)","Velur","Mikrofiber","Bukle","Shenil"] },
      { key: "itemType",   label: "Turi",                type: "select",  options: ["Divan (klassik)","L-shakl burchak divan","Kreslo (klassik)","Kreslo (aylanadigan)","Ottoman","Modul divan"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Kulrang, Bej, To'q jigarrang" },
      { key: "length",     label: "Uzunligi (eni)",        type: "number",  unit: "sm",  placeholder: "220" },
      { key: "depth",      label: "Chuqurligi",           type: "number",  unit: "sm",  placeholder: "90" },
      { key: "seats",      label: "O'tirish joylari",     type: "select",  options: ["1","2","3","4","5","6+","Modul"] },
      { key: "foldable",   label: "Yotiladigan (razkladnoy)", type: "toggle" },
      { key: "storage",    label: "Qutilar bilan (ichida)", type: "toggle" },
    ],
  },
  {
    names: ["Stol va stullar", "Stollar", "Stullar"], emoji: "🍽️",
    fields: [
      { key: "corpusMat",  label: "Oyoqlar materiali",    type: "select", options: ["Metall profil","Eman massiv","MDF","Plastik","Chrome metall","Kombinatsiya"] },
      { key: "facadeMat",  label: "Stol yuzasi materiali", type: "select", options: ["Eman massiv","MDF + laminat","Shisha (tempered)","Mramor","Granit","Keramika","LDSP","Kvarts"] },
      { key: "tableType",  label: "Stol turi",            type: "select",  options: ["Ovqat stoli","Kofe stoli","Yozuv stoli","Jurnal stoli","Burchak stoli","Transformerli","Stul"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Qora, Oq, Yog'och" },
      { key: "length",     label: "Uzunligi",             type: "number",  unit: "sm",  placeholder: "160" },
      { key: "width",      label: "Eni",                  type: "number",  unit: "sm",  placeholder: "90" },
      { key: "height",     label: "Balandligi",           type: "number",  unit: "sm",  placeholder: "76" },
      { key: "extendable", label: "Kengaytiriladigan", type: "toggle" },
      { key: "chairs",     label: "Stullar bilan birga",  type: "toggle" },
    ],
  },
  {
    names: ["Bolalar mebellar", "Bola xonasi"], emoji: "🧸",
    fields: [
      { key: "corpusMat",  label: "Korpus materiali",     type: "select", options: ["LDSP Laminat (xavfsiz)","MDF (xavfsiz)","Eman massiv","Sosna massiv","Plastik (sertifikatlangan)"] },
      { key: "setType",    label: "Garnitur turi",        type: "select",  options: ["To'liq garnitur","Faqat karavot","Burchak karavot","Stol + stul","Shkaf","Ikki qavatli karavot"] },
      { key: "ageGroup",   label: "Yosh guruh",           type: "select",  options: ["0–3 yosh","3–7 yosh","7–12 yosh","12–17 yosh","Universal"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Oq, Pushti, Ko'k" },
      { key: "bedSize",    label: "Karavot o'lchami",     type: "select",  options: ["60×120","70×140","80×160","80×200","90×200"] },
      { key: "safeCoat",   label: "Xavfsiz ekologik lak", type: "toggle" },
      { key: "storage",    label: "Tortmachalar bilan",   type: "toggle" },
      { key: "bunk",       label: "Ikki qavatli",         type: "toggle" },
    ],
  },
  {
    names: ["Ofis mebellar", "Ofis mebeli"], emoji: "🖥️",
    fields: [
      { key: "corpusMat",  label: "Korpus materiali",     type: "select", options: KORPUS_OPTS },
      { key: "officeType", label: "Mebelning turi",       type: "select",  options: ["Ish stoli","Ofis kreslo","Kitob javoni","Garnitur","Qabul stoli","Kutish xonasi divani"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Kulrang, Qora, Yong'oq" },
      { key: "deskW",      label: "Stol eni",             type: "number",  unit: "sm",  placeholder: "160" },
      { key: "deskD",      label: "Stol chuqurligi",      type: "number",  unit: "sm",  placeholder: "70" },
      { key: "deskH",      label: "Stol balandligi",      type: "number",  unit: "sm",  placeholder: "76" },
      { key: "pedestal",   label: "Pedestal bilan",       type: "toggle" },
      { key: "cable",      label: "Sim boshqaruv tizimi", type: "toggle" },
    ],
  },
  {
    names: ["Vannaxona mebellar", "Vannaxona mebeli"], emoji: "🚿",
    fields: [
      { key: "corpusMat",  label: "Korpus materiali",     type: "select", options: ["MDF (suv o'tkazmaydigan)","PVC plastik","Alyuminiy","Eman massiv (lakli)","Kombinatsiya"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Oq, Kulrang" },
      { key: "setType",    label: "To'plam turi",         type: "select",  options: ["To'liq garnitur","Faqat shkaf","Mirror shkaf","Lavabo + tumba","Hammom shkafi"] },
      { key: "width",      label: "Eni",                  type: "number",  unit: "sm",  placeholder: "80" },
      { key: "height",     label: "Balandligi",           type: "number",  unit: "sm",  placeholder: "55" },
      { key: "sink",       label: "Lavabo bilan",         type: "toggle" },
      { key: "mirror",     label: "Ko'zgu bilan",         type: "toggle" },
      { key: "waterproof", label: "Suv o'tkazmaydigan",   type: "toggle" },
    ],
  },
  {
    names: ["Matraslar"], emoji: "💤",
    fields: [
      { key: "matType",    label: "Matras turi",          type: "select",  options: ["Yay (prujina) bilan","Prujinasiz","Ortopedik","Memory foam","Lateks","Kokonut","Gibrid"] },
      { key: "size",       label: "O'lcham",              type: "select",  options: ["90×200","160×220","180×220","170×210"] },
      { key: "thickness",  label: "Qalinligi",            type: "number",  unit: "sm",  placeholder: "20" },
      { key: "firmness",   label: "Qattiqlik darajasi",   type: "select",  options: ["Juda yumshoq","Yumshoq","O'rta-yumshoq","O'rta","O'rta-qattiq","Qattiq"] },
      { key: "filling",    label: "Ichki material",       type: "select",  options: ["Memory foam","Lateks (tabiiy)","Lateks (sintetik)","Kokonut","Yay: Bonnel","Yay: Pocket","Gibrid"] },
      { key: "removeCover",label: "Qoplama yechish mumkin", type: "toggle" },
      { key: "twoSides",   label: "Ikki tomonlama",       type: "toggle" },
    ],
  },
  {
    names: ["Ko'rpalar va yostiqlar", "Dekorativ yostiqlar"], emoji: "🛏️",
    fields: [
      { key: "itemType",   label: "Mahsulot turi",        type: "select",  options: ["Ko'rpa (odeyalo)","Yostiq","Ko'rpa-yostiq to'plami","Dekorativ yostiq"] },
      { key: "filling",    label: "To'ldirma materiali",  type: "select",  options: ["Paxta","Sintepon","Hollofayber","Bambuk","Lateks","Memory foam","Gus pati","Mikrofiber"] },
      { key: "size",       label: "O'lcham",              type: "select",  options: ["30×30 (dekor)","40×40","50×70 (yostiq)","140×200 (1.5 sp)","175×210 (2 sp)","200×220 (evro)"] },
      { key: "warmth",     label: "Iliqlik",              type: "select",  options: ["Yozgi (yengil)","Bahor/Kuz (o'rtacha)","Qishki (issiq)","Juda issiq"] },
      { key: "washable",   label: "Mashinada yuviladi",   type: "toggle" },
    ],
  },
  {
    names: ["Choyshab to'plamlar"], emoji: "🛏️",
    fields: [
      { key: "material",   label: "Mato materiali",       type: "select",  options: ["100% paxta","Ranforce","Satin","Baxmal","Bambuk","Mikrofibra","Flannel","Perkal"] },
      { key: "size",       label: "O'lcham",              type: "select",  options: ["1.5 sp (140×200)","2 sp (175×210)","Evro (200×220)","King (220×240)","Bola (110×140)"] },
      { key: "pieces",     label: "To'plamdagi qismlar",  type: "select",  options: ["3 ta","4 ta","5 ta","6 ta","8 ta"] },
      { key: "color",      label: "Rang / Naqsh",         type: "text",    placeholder: "masalan: Oq, Ko'k chiziqli" },
      { key: "fade",       label: "Rang tushmaydigan",    type: "toggle" },
    ],
  },
  {
    names: ["Uy pardalar", "Pardalar"], emoji: "🪟",
    fields: [
      { key: "curtainType",label: "Parda turi",           type: "select",  options: ["Klassik (to'r)","Portyer (og'ir)","Rimlyan (rollo)","Zhalyuzi","Blakaut (tunda)","Organza"] },
      { key: "material",   label: "Mato materiali",       type: "select",  options: ["Paxta","Poliester","Linen","Velur","Organza","Blakaut","Tül (to'r)"] },
      { key: "color",      label: "Rangi / Naqshi",       type: "text",    placeholder: "masalan: Kulrang, Bej, Oq geometrik" },
      { key: "width",      label: "Eni (1 kanat)",        type: "number",  unit: "sm",  placeholder: "140" },
      { key: "height",     label: "Balandligi",           type: "number",  unit: "sm",  placeholder: "260" },
      { key: "blackout",   label: "To'liq qoraytiradigan", type: "toggle" },
      { key: "washable",   label: "Mashinada yuviladi",   type: "toggle" },
    ],
  },
  {
    names: ["Muzlatgichlar"], emoji: "🧊",
    fields: [
      { key: "brand",      label: "Brend",                type: "text",    placeholder: "masalan: Samsung, LG, Artel" },
      { key: "fridgeType", label: "Turi",                 type: "select",  options: ["Ikki kamerali","Bir kamerali","Side-by-Side","French Door","Mini (stol osti)","No Frost"] },
      { key: "totalVol",   label: "Hajm",                 type: "number",  unit: "litr", placeholder: "360" },
      { key: "color",      label: "Rangi",                type: "select",  options: ["Oq","Kumush (inox)","Qora","Kulrang","Boshqa"] },
      { key: "height",     label: "Balandligi",           type: "number",  unit: "sm",  placeholder: "185" },
      { key: "energyClass",label: "Energiya sinfi",       type: "select",  options: ["A+++","A++","A+","A","B","C"] },
      { key: "nofrost",    label: "No Frost",             type: "toggle" },
      { key: "inverter",   label: "Inverter kompressor",  type: "toggle" },
      { key: "warranty",   label: "Kafolat",              type: "select",  options: ["1 yil","2 yil","3 yil","5 yil"] },
    ],
  },
  {
    names: ["Kir yuvish mashinalari"], emoji: "🫧",
    fields: [
      { key: "brand",      label: "Brend",                type: "text",    placeholder: "masalan: Samsung, LG, Bosch" },
      { key: "washType",   label: "Yuklash turi",         type: "select",  options: ["Old tomondan (frontal)","Yuqoridan (vertikal)"] },
      { key: "capacity",   label: "Sig'imi",              type: "select",  options: ["3.5 kg","4 kg","5 kg","6 kg","7 kg","8 kg","9 kg","10 kg","12 kg"] },
      { key: "rpm",        label: "Aylanish tezligi",     type: "select",  options: ["800 ayl/min","1000 ayl/min","1200 ayl/min","1400 ayl/min"] },
      { key: "energyClass",label: "Energiya sinfi",       type: "select",  options: ["A+++","A++","A+","A","B"] },
      { key: "steam",      label: "Bug' funksiyasi",      type: "toggle" },
      { key: "inverter",   label: "Inverter motor",       type: "toggle" },
      { key: "dryer",      label: "Quritish funksiyasi",  type: "toggle" },
    ],
  },
  {
    names: ["Televizorlar"], emoji: "📺",
    fields: [
      { key: "brand",      label: "Brend",                type: "text",    placeholder: "masalan: Samsung, LG, Sony" },
      { key: "screen",     label: "Ekran o'lchami",       type: "select",  options: ["32\"","43\"","50\"","55\"","65\"","75\"","85\"","100\"+"] },
      { key: "resolution", label: "Ruxsat (Rezolutsiya)", type: "select",  options: ["HD (1280×720)","Full HD (1920×1080)","4K UHD","8K UHD"] },
      { key: "panelType",  label: "Panel turi",           type: "select",  options: ["IPS (LED)","VA (LED)","OLED","QLED","Mini LED"] },
      { key: "smart",      label: "Smart TV",             type: "toggle" },
      { key: "hdr",        label: "HDR qo'llab-quvvatlash", type: "toggle" },
      { key: "warranty",   label: "Kafolat",              type: "select",  options: ["1 yil","2 yil","3 yil"] },
    ],
  },
  {
    names: ["Konditsionerlar"], emoji: "🌬️",
    fields: [
      { key: "brand",      label: "Brend",                type: "text",    placeholder: "masalan: Midea, Gree, Samsung" },
      { key: "capacity",   label: "Sovutish quvvati",     type: "select",  options: ["7000 BTU (9 m²)","9000 BTU (12 m²)","12000 BTU (18 m²)","18000 BTU (25 m²)","24000 BTU (35 m²)","36000 BTU (50 m²+)"] },
      { key: "energyClass",label: "Energiya sinfi",       type: "select",  options: ["A+++","A++","A+","A","B"] },
      { key: "inverter",   label: "Inverter",             type: "toggle" },
      { key: "heating",    label: "Isitish funksiyasi",   type: "toggle" },
      { key: "wifi",       label: "Wi-Fi boshqaruv",      type: "toggle" },
      { key: "warranty",   label: "Kafolat",              type: "select",  options: ["1 yil","2 yil","3 yil","5 yil"] },
    ],
  },
  {
    names: ["Oshxona texnikasi"], emoji: "🍳",
    fields: [
      { key: "brand",      label: "Brend",                type: "text",    placeholder: "masalan: Tefal, Bosch, Artel" },
      { key: "itemType",   label: "Texnika turi",         type: "select",  options: ["Plita (gazli)","Plita (elektr)","Tandircha (o'choq)","Qovurma (elektr)","Ovqat pishirgich","Blender","Mikser","Non pishirgich","Qahva mashinasi"] },
      { key: "power",      label: "Quvvati",              type: "number",  unit: "W",   placeholder: "1500" },
      { key: "capacity",   label: "Sig'imi",              type: "text",    placeholder: "masalan: 6 L" },
      { key: "warranty",   label: "Kafolat",              type: "select",  options: ["1 yil","2 yil","3 yil"] },
    ],
  },
  {
    names: ["Changyutgich"], emoji: "🧹",
    fields: [
      { key: "brand",      label: "Brend",                type: "text",    placeholder: "masalan: Dyson, Samsung, LG" },
      { key: "type",       label: "Turi",                 type: "select",  options: ["Simsiz (akkumulyator)","Simli (kuchli)","Robot changyutgich","Namlash funksiyali"] },
      { key: "power",      label: "Quvvati",              type: "number",  unit: "W",   placeholder: "2000" },
      { key: "bagless",    label: "Sumkasiz (tsiklonik)",  type: "toggle" },
      { key: "warranty",   label: "Kafolat",              type: "select",  options: ["1 yil","2 yil","3 yil"] },
    ],
  },
  {
    names: ["Isitgich va ventilyator"], emoji: "🌡️",
    fields: [
      { key: "brand",      label: "Brend",                type: "text",    placeholder: "masalan: Ballu, Polaris, Toshiba" },
      { key: "itemType",   label: "Turi",                 type: "select",  options: ["Elektr isitgich","Infra qizil isitgich","Yog'li radiator","Ventilyator (stol)","Ventilyator (polga qo'yiladigan)","Konditsioner isitgich"] },
      { key: "power",      label: "Quvvati",              type: "number",  unit: "W",   placeholder: "2000" },
      { key: "thermostat", label: "Termostat",            type: "toggle" },
      { key: "remote",     label: "Pult bilan",           type: "toggle" },
    ],
  },
  {
    names: ["Idish-tovoq"], emoji: "🍽️",
    fields: [
      { key: "material",   label: "Materiali",            type: "select",  options: ["Chinni","Shisha","Metall (zanglamaydigan)","Plastik (xavfsiz)","Keramika","Granit"] },
      { key: "pieces",     label: "To'plamdagi qismlar",  type: "select",  options: ["6 ta","12 ta","24 ta","36 ta","48+"] },
      { key: "color",      label: "Rangi / Naqshi",       type: "text",    placeholder: "masalan: Oq, Ko'k naqshli, Oltin chegarali" },
      { key: "washable",   label: "Posudamoyda yuviladi", type: "toggle" },
      { key: "microwave",  label: "Mikro to'lqinda ishlatiladi", type: "toggle" },
    ],
  },
  {
    names: ["Pishirish idishlari"], emoji: "🥘",
    fields: [
      { key: "material",   label: "Materiali",            type: "select",  options: ["Granit anti-yopishmas","Keramik anti-yopishmas","Temir (quyma)","Zanglamaydigan po'lat","Titan qoplama","Alyuminiy"] },
      { key: "pieces",     label: "To'plam",              type: "select",  options: ["1 ta","3 ta","5 ta","7 ta","9 ta"] },
      { key: "size",       label: "O'lcham (diametr)",    type: "select",  options: ["20 sm","22 sm","24 sm","26 sm","28 sm","30 sm+"] },
      { key: "induction",  label: "Induktsion plita uchun", type: "toggle" },
      { key: "oven",       label: "Duxovka uchun",        type: "toggle" },
    ],
  },
  {
    names: ["Gilamlar"], emoji: "🎨",
    fields: [
      { key: "rugType",    label: "Gilam turi",           type: "select",  options: ["Mashinada to'qilgan","Qo'lda to'qilgan","Tafted","Kilim (yassi)","Shenil","Shaggy (uzun tuk)"] },
      { key: "material",   label: "Tolasi",               type: "select",  options: ["Poliester","Akril","Polipropilen","Jun (wool)","Ipak","Bambuk","Viskoza"] },
      { key: "size",       label: "O'lcham",              type: "select",  options: ["60×110","80×150","100×200","120×180","150×200","160×230","200×300","Maxsus"] },
      { key: "pile",       label: "Tuk balandligi",       type: "select",  options: ["Tuksiz","Past (6–8 mm)","O'rta (10–15 mm)","Baland (20–30 mm)","Juda baland (40mm+)"] },
      { key: "color",      label: "Asosiy rang / naqsh",  type: "text",    placeholder: "masalan: Bej geometrik" },
      { key: "antislip",   label: "Slipmay (asoslangan)", type: "toggle" },
      { key: "washable",   label: "Mashinada yuviladi",   type: "toggle" },
    ],
  },
  {
    names: ["Shiftlar (lyustra)", "Chiroqlar", "Devor chiroqlari", "Stol va pol chiroqlari"], emoji: "💡",
    fields: [
      { key: "lightType",  label: "Chiroq turi",          type: "select",  options: ["Lyustra (shiftga)","Bra (devorga)","Torshyer (polda)","Stol chiroqi","Spot (nuqtaviy)","LED panel","Track light"] },
      { key: "style",      label: "Dizayn uslubi",        type: "select",  options: ["Zamonaviy (modern)","Skandinavcha","Klassik","Loft / Industrial","Minimalizm","Art Deco"] },
      { key: "material",   label: "Korpus materiali",     type: "select",  options: ["Metall xrom","Metall qora","Bronza / Oltin","Shisha + metall","Akrilik","Qog'oz / Mato"] },
      { key: "colorTemp",  label: "Rang harorati",        type: "select",  options: ["2700K – Issiq oq","3000K – Iliq oq","4000K – Tabiiy oq","5000–6500K – Sovuq oq"] },
      { key: "power",      label: "Quvvati",              type: "number",  unit: "W",   placeholder: "40" },
      { key: "diameter",   label: "Diametr / Eni",        type: "number",  unit: "sm",  placeholder: "60" },
      { key: "dimmable",   label: "Dimmer bilan",         type: "toggle" },
      { key: "remote",     label: "Pult bilan",           type: "toggle" },
      { key: "bulbIncl",   label: "Lampa kiritilgan",     type: "toggle" },
    ],
  },
  {
    names: ["LED va smart chiroqlar"], emoji: "🔆",
    fields: [
      { key: "ledType",    label: "LED turi",             type: "select",  options: ["LED lenta","Smart lampa (WiFi)","Spot LED","LED panel","RGB lenta","CCT lampa"] },
      { key: "power",      label: "Quvvati",              type: "number",  unit: "W",   placeholder: "12" },
      { key: "colorTemp",  label: "Rang harorati",        type: "select",  options: ["2700K – Issiq oq","4000K – Tabiiy oq","5000K – Sovuq oq","RGB (ko'p rangni)"] },
      { key: "length",     label: "Uzunligi (lenta)",     type: "number",  unit: "m",   placeholder: "5" },
      { key: "smart",      label: "Smart (WiFi/Bluetooth)", type: "toggle" },
      { key: "dimmable",   label: "Dimmer bilan",         type: "toggle" },
      { key: "remote",     label: "Pult bilan",           type: "toggle" },
    ],
  },
  {
    names: ["Ko'cha va bog' chiroqlar"], emoji: "🌟",
    fields: [
      { key: "lightType",  label: "Chiroq turi",          type: "select",  options: ["Ko'cha lyustra","Devor (fasad) chiroq","Yerga qo'yiladigan","Solar (quyosh)","Gazon chiroqlari"] },
      { key: "power",      label: "Quvvati",              type: "number",  unit: "W",   placeholder: "20" },
      { key: "material",   label: "Korpus materiali",     type: "select",  options: ["Alyuminiy (IP65)","Zanglamaydigan po'lat","Plastik (IP54)","Tempered shisha"] },
      { key: "solar",      label: "Quyosh batareyali",    type: "toggle" },
      { key: "sensor",     label: "Harakat sensori",      type: "toggle" },
      { key: "waterproof", label: "Suv o'tkazmaydigan (IP65+)", type: "toggle" },
    ],
  },
  {
    names: ["Hovli mebellar"], emoji: "🪑",
    fields: [
      { key: "material",   label: "Materiali",            type: "select",  options: ["Alyuminiy","Temir (bo'yalgan)","Yog'och (teak/sosna)","Polirattan (sintetik)","Plastik (UV bardosh)","Kompozit"] },
      { key: "setType",    label: "To'plam turi",         type: "select",  options: ["Stol + stullar","Divan (ko'cha)","Kreslo (ko'cha)","Shezlong","Salınqalı (skamelka)","To'liq garnitur"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Kulrang, Qora, Jigarrang" },
      { key: "foldable",   label: "Bukiladigan",          type: "toggle" },
      { key: "weatherRes", label: "Ob-havoga bardosh",    type: "toggle" },
    ],
  },
  {
    names: ["Bog' uskunalari"], emoji: "🌱",
    fields: [
      { key: "itemType",   label: "Uskuna turi",          type: "select",  options: ["Qazuvchi kichik asbob","Qo'l kesuvchi (pruner)","Erta kesish mashinasi","Elektr kesuvchi","Sug'orish nasosi","O'tkazma (trychovka)"] },
      { key: "material",   label: "Materiali",            type: "select",  options: ["Zanglamaydigan po'lat","Karbid po'lat","Plastik tutqich","Yog'och tutqich","Alyuminiy"] },
      { key: "electric",   label: "Elektr bilan ishlaydi", type: "toggle" },
      { key: "set",        label: "To'plam holida",       type: "toggle" },
    ],
  },
  {
    names: ["Pol qoplamalar"], emoji: "🪵",
    fields: [
      { key: "floorType",  label: "Qoplama turi",         type: "select",  options: ["Laminat","Parket (massiv)","Vinilova plitka (SPC/LVT)","Linoleum","Keramika plitka","Granit plitka","Kork"] },
      { key: "material",   label: "Materiali",            type: "select",  options: ["HDF (yuqori zichlik)","Eman massiv","O'riq","MDF","Vinil","PVC","Keramika","Porselan"] },
      { key: "thickness",  label: "Qalinligi",            type: "number",  unit: "mm",  placeholder: "12" },
      { key: "wearClass",  label: "Yeyilishga chidamlilik", type: "select", options: ["AC3 (xona)","AC4 (ofis)","AC5 (savdo zali)"] },
      { key: "waterproof", label: "Suv o'tkazmaydigan",   type: "toggle" },
      { key: "underfloor", label: "Yerosti isitish uchun", type: "toggle" },
    ],
  },
  {
    names: ["Devor qoplamalar"], emoji: "🧱",
    fields: [
      { key: "wallType",   label: "Qoplama turi",         type: "select",  options: ["Tapeta","3D panel","Dekorativ gips","Dekorativ tosh","Keramika plitka","Mozaika","Bambuk / Yog'och panel"] },
      { key: "material",   label: "Materiali",            type: "select",  options: ["Vinil tapeta","Non-woven tapeta","Fiberglass (shisha tolasi)","Gips panel","Keramika","Tabiiy tosh","Yog'och"] },
      { key: "width",      label: "Eni (rulon)",          type: "number",  unit: "sm",  placeholder: "106" },
      { key: "length",     label: "Uzunligi (rulon)",     type: "number",  unit: "m",   placeholder: "10" },
      { key: "washable",   label: "Yuviladi",             type: "toggle" },
      { key: "peel",       label: "O'z-o'zidan yopishadi", type: "toggle" },
    ],
  },
  {
    names: ["Bo'yoqlar va laklar"], emoji: "🎨",
    fields: [
      { key: "paintType",  label: "Bo'yoq turi",          type: "select",  options: ["Akril (suv asosida)","Latex","Emulsion","Yog' asosidagi (emal)","Epoksi","Lak (shaffof)","Grunt (asosiy qatlam)"] },
      { key: "surface",    label: "Ishlatiladigan yuza",  type: "select",  options: ["Devor va shift","Tashqi devor","Temir va metall","Yog'och","Universal"] },
      { key: "volume",     label: "Hajmi",                type: "select",  options: ["1 L","2.5 L","5 L","10 L","15 L","20 L"] },
      { key: "finish",     label: "Jilo turi",            type: "select",  options: ["Matt","Yarim matt","Satin","Yarim jiloli","Jiloli (gloss)"] },
      { key: "color",      label: "Rangi (RAL kodi yoki tavsifi)", type: "text", placeholder: "masalan: Oq RAL 9010" },
    ],
  },
  {
    names: ["Santexnika"], emoji: "🚿",
    fields: [
      { key: "itemType",   label: "Mahsulot turi",        type: "select",  options: ["Unitaz","Lavabo (kichik)","Lavabo (katta)","Vanna (cho'milish)","Dush kabinasi","Kran (aralashtirgich)","Shtanga (dush uchun)","Isitgich (suv uchun)"] },
      { key: "material",   label: "Materiali",            type: "select",  options: ["Santexnik farfor","Keramika","Akrilik","Zanglamaydigan po'lat","Bronza/Mis","Plastik"] },
      { key: "color",      label: "Rangi",                type: "select",  options: ["Oq","Kulrang (Taupe)","Qora (Matt)","Oltin","Kumush","Boshqa"] },
      { key: "width",      label: "Eni",                  type: "number",  unit: "sm",  placeholder: "60" },
      { key: "warranty",   label: "Kafolat",              type: "select",  options: ["1 yil","2 yil","3 yil","5 yil"] },
    ],
  },
  {
    names: ["Eshik va derazalar"], emoji: "🚪",
    fields: [
      { key: "itemType",   label: "Mahsulot turi",        type: "select",  options: ["Ichki eshik","Kirish eshik (metal)","Plastik deraza (PVC)","Alyuminiy deraza","Balkon bloki","Eshik asboblari"] },
      { key: "material",   label: "Asosiy materiali",     type: "select",  options: ["MDF (plitka qoplama)","Eman massiv","Sosna massiv","PVC plastik","Alyuminiy","Po'lat (metal)","Shisha + metall"] },
      { key: "width",      label: "Eni",                  type: "number",  unit: "mm",  placeholder: "900" },
      { key: "height",     label: "Balandligi",           type: "number",  unit: "mm",  placeholder: "2000" },
      { key: "color",      label: "Rangi / Qaplamai",     type: "text",    placeholder: "masalan: Oq, Wenge, Yong'oq" },
      { key: "glass",      label: "Shisha mavjud",        type: "toggle" },
      { key: "lock",       label: "Qulf to'plami bilan",  type: "toggle" },
      { key: "soundproof", label: "Tovush o'tkazmaydigan", type: "toggle" },
    ],
  },
  {
    names: ["Rasmlar va suratlar"], emoji: "🖼️",
    fields: [
      { key: "artType",    label: "Turi",                 type: "select",  options: ["Yog' bo'yoq","Akvarell","Grafika (chizma)","Foto print","3D poster","Keramika panel","Ko'zgu doira"] },
      { key: "width",      label: "Eni",                  type: "number",  unit: "sm",  placeholder: "60" },
      { key: "height",     label: "Balandligi",           type: "number",  unit: "sm",  placeholder: "80" },
      { key: "frame",      label: "Ramka mavjud",         type: "toggle" },
      { key: "handmade",   label: "Qo'l ishi",            type: "toggle" },
    ],
  },
  {
    names: ["Vazalar va guldanlar", "Devor soatlari", "Dasturxon bezaklari", "Tozalash buyumlari", "Saqlash va tartib", "Hammom aksessuarlar", "Barbeque va piknik", "Suv ta'minoti", "Hovli va bog' bezak", "Elektr materiallari", "Bog' uskunalari"], emoji: "✨",
    fields: [
      { key: "material",   label: "Materiali",            type: "select",  options: ["Shisha","Keramika","Metall","Plastik","Yog'och","Chinni","Boshqa"] },
      { key: "color",      label: "Rangi",                type: "text",    placeholder: "masalan: Oq, Oltin, Kulrang" },
    ],
  },

  // ── ELEKTRONIKA ──────────────────────────────────────────────────────────────
  {
    names: ["Smartfonlar"], emoji: "📱",
    fields: [
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Samsung, Apple, Xiaomi, Huawei" },
      { key: "model",     label: "Model",              type: "text",   placeholder: "Galaxy S24, iPhone 15..." },
      { key: "storage",   label: "Xotira",             type: "select", options: ["32 GB", "64 GB", "128 GB", "256 GB", "512 GB", "1 TB"] },
      { key: "ram",       label: "RAM",                type: "select", options: ["2 GB", "4 GB", "6 GB", "8 GB", "12 GB", "16 GB"] },
      { key: "screen",    label: "Ekran o'lchami",     type: "number", unit: "inch", placeholder: "6.1" },
      { key: "color",     label: "Rangi",              type: "text",   placeholder: "Qora, Oq, Ko'k, Qizil" },
      { key: "condition", label: "Holati",             type: "select", options: ["Yangi (muhr yopiq)", "Yangi (ochirilgan)", "Ishlatilgan (A+)", "Ishlatilgan (A)"] },
      { key: "simCount",  label: "SIM karta soni",     type: "select", options: ["1 SIM", "2 SIM", "eSIM"] },
    ],
  },
  {
    names: ["Noutbuklar"], emoji: "💻",
    fields: [
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Lenovo, HP, Dell, Apple, Asus" },
      { key: "cpu",       label: "Protsessor",         type: "text",   placeholder: "Intel Core i5-12500H, AMD Ryzen 5..." },
      { key: "ram",       label: "RAM",                type: "select", options: ["4 GB", "8 GB", "16 GB", "32 GB", "64 GB"] },
      { key: "storage",   label: "Qattiq disk",        type: "text",   placeholder: "512 GB SSD, 1 TB HDD..." },
      { key: "screen",    label: "Ekran",              type: "number", unit: "inch", placeholder: "15.6" },
      { key: "gpu",       label: "Grafik karta",       type: "text",   placeholder: "NVIDIA RTX 3050, Intel UHD..." },
      { key: "os",        label: "Operatsion tizim",   type: "select", options: ["Windows 11", "Windows 10", "macOS", "Ubuntu/Linux", "FreeDOS"] },
      { key: "color",     label: "Rangi",              type: "text",   placeholder: "Kulrang, Qora, Kumush" },
      { key: "condition", label: "Holati",             type: "select", options: ["Yangi", "Ishlatilgan (A+)", "Ishlatilgan (A)"] },
    ],
  },
  {
    names: ["Planshetlar"], emoji: "📲",
    fields: [
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Apple, Samsung, Huawei, Xiaomi" },
      { key: "model",     label: "Model",              type: "text",   placeholder: "iPad 10, Galaxy Tab S9..." },
      { key: "storage",   label: "Xotira",             type: "select", options: ["32 GB", "64 GB", "128 GB", "256 GB", "512 GB"] },
      { key: "ram",       label: "RAM",                type: "select", options: ["2 GB", "3 GB", "4 GB", "6 GB", "8 GB", "12 GB"] },
      { key: "screen",    label: "Ekran o'lchami",     type: "number", unit: "inch", placeholder: "10.9" },
      { key: "sim",       label: "SIM karta",          type: "select", options: ["Yo'q (Wi-Fi only)", "1 SIM + Wi-Fi"] },
      { key: "color",     label: "Rangi",              type: "text",   placeholder: "Kumush, Kulrang, Qora" },
      { key: "condition", label: "Holati",             type: "select", options: ["Yangi", "Ishlatilgan (A+)", "Ishlatilgan (A)"] },
    ],
  },
  {
    names: ["Televizorlar"], emoji: "📺",
    fields: [
      { key: "brend",      label: "Brend",             type: "text",   placeholder: "Samsung, LG, Sony, Hisense, Artel" },
      { key: "diagonal",   label: "Diagonal",          type: "select", options: ['32"', '43"', '50"', '55"', '65"', '75"', '85"'] },
      { key: "tech",       label: "Texnologiya",       type: "select", options: ["LED", "QLED", "OLED", "Mini LED", "AMOLED"] },
      { key: "resolution", label: "Razreshenie",       type: "select", options: ["HD (1366x768)", "Full HD (1920x1080)", "4K Ultra HD", "8K"] },
      { key: "smart",      label: "Smart TV",          type: "toggle" },
      { key: "refresh",    label: "Yangilanish tezligi", type: "select", options: ["50 Hz", "60 Hz", "100 Hz", "120 Hz"] },
    ],
  },
  {
    names: ["Audio texnika"], emoji: "🎧",
    fields: [
      { key: "brend",       label: "Brend",            type: "text",   placeholder: "JBL, Sony, Samsung, Bose, Xiaomi" },
      { key: "type",        label: "Tur",              type: "select", options: ["Simsiz quloqchin (TWS)", "Simli quloqchin", "Bluetooth kolonka", "Uy kino tizimi", "Pleyar"] },
      { key: "connection",  label: "Ulanish",          type: "select", options: ["Bluetooth 5.0+", "Bluetooth 4.2", "Simli (3.5mm)", "Simli (USB-C)", "Wi-Fi"] },
      { key: "power",       label: "Quvvati",          type: "number", unit: "W", placeholder: "20" },
      { key: "battery",     label: "Batareya muddati", type: "text",   placeholder: "masalan: 30 soat" },
      { key: "noiseCancel", label: "Shovqin bloklash (ANC)", type: "toggle" },
    ],
  },
  {
    names: ["Kamera va foto"], emoji: "📷",
    fields: [
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Canon, Nikon, Sony, GoPro, DJI" },
      { key: "type",      label: "Tur",                type: "select", options: ["DSLR kamera", "Sizsiz (mirrorless)", "Kompakt kamera", "Aksiyon kamera", "Dron kamera", "Veb-kamera"] },
      { key: "mp",        label: "Megapiksel",         type: "number", unit: "MP", placeholder: "24" },
      { key: "zoom",      label: "Optik zoom",         type: "text",   placeholder: "masalan: 10x, 20x" },
      { key: "stabiliz",  label: "OIS (tasvirni barqarorlashtirish)", type: "toggle" },
      { key: "video",     label: "Video sifati",       type: "select", options: ["Full HD (1080p)", "4K", "4K 60fps", "8K"] },
      { key: "condition", label: "Holati",             type: "select", options: ["Yangi", "Ishlatilgan (A+)", "Ishlatilgan (A)"] },
    ],
  },
  {
    names: ["Smartwatch va tracker"], emoji: "⌚",
    fields: [
      { key: "brend",   label: "Brend",                type: "text",   placeholder: "Apple, Samsung, Xiaomi, Huawei, Amazfit" },
      { key: "type",    label: "Tur",                  type: "select", options: ["Smart soat", "Fitness tracker", "Sport soat", "Bolalar soati"] },
      { key: "compat",  label: "Moslik",               type: "select", options: ["Android", "iOS (Apple)", "Android va iOS", "Universal"] },
      { key: "screen",  label: "Ekran diagonali",      type: "number", unit: "mm", placeholder: "44" },
      { key: "water",   label: "Suv himoyasi",         type: "select", options: ["Yo'q", "IP67", "IP68", "5ATM", "10ATM"] },
      { key: "battery", label: "Batareya muddati",     type: "text",   placeholder: "masalan: 7 kun, 14 kun" },
      { key: "color",   label: "Rangi",                type: "text",   placeholder: "Qora, Kumush, Oltin" },
    ],
  },
  // ── KIYIMLAR ─────────────────────────────────────────────────────────────────
  {
    names: ["Erkaklar kiyimlari"], emoji: "👔",
    fields: [
      { key: "type",     label: "Kiyim turi",          type: "select", options: ["Ko'ylak", "Futbolka", "Polo", "Trening", "Shim (jins)", "Shim (klassik)", "Kurtka", "Palto", "Kostyum", "Sviter", "Hoodie", "Jaket", "Shorts"] },
      { key: "size",     label: "O'lchami",            type: "select", options: ["XS (44)", "S (46)", "M (48)", "L (50)", "XL (52)", "2XL (54)", "3XL (56)", "4XL (58)"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Qora, Oq, Ko'k, Kulrang" },
      { key: "material", label: "Matosi",              type: "select", options: ["Paxta (100%)", "Poliester", "Paxta + Poliester", "Zig'ir (linen)", "Junli", "Jins (denim)", "Charm"] },
      { key: "season",   label: "Mavsumi",             type: "select", options: ["Bahor-Kuz", "Yoz", "Qish", "Universal"] },
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "masalan: Zara, H&M, Mango, Adidas" },
    ],
  },
  {
    names: ["Ayollar kiyimlari"], emoji: "👗",
    fields: [
      { key: "type",     label: "Kiyim turi",          type: "select", options: ["Ko'ylak", "Bluzka", "Futbolka", "Yubka", "Shim", "Jins", "Platye", "Kurtka", "Palto", "Sviter", "Hoodie", "Kombinezon"] },
      { key: "size",     label: "O'lchami",            type: "select", options: ["XS (42)", "S (44)", "M (46)", "L (48)", "XL (50)", "2XL (52)", "3XL (54)"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Qora, Oq, Pushti, Ko'k" },
      { key: "material", label: "Matosi",              type: "select", options: ["Paxta (100%)", "Poliester", "Viscoza", "Shifon", "Jins (denim)", "Junli", "Charm"] },
      { key: "season",   label: "Mavsumi",             type: "select", options: ["Bahor-Kuz", "Yoz", "Qish", "Universal"] },
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "masalan: Zara, H&M, Mango" },
    ],
  },
  {
    names: ["Bolalar kiyimlari"], emoji: "👶",
    fields: [
      { key: "type",     label: "Kiyim turi",          type: "select", options: ["Futbolka", "Ko'ylak", "Shim", "Kurtka", "Palto", "Pijama", "Kombinezon", "Trening", "Platye", "Sviter"] },
      { key: "age",      label: "Yoshi (yil)",         type: "select", options: ["0-1 yosh", "1-2 yosh", "2-3 yosh", "3-4 yosh", "4-5 yosh", "5-6 yosh", "6-7 yosh", "7-8 yosh", "8-10 yosh", "10-12 yosh", "12-14 yosh", "14-16 yosh"] },
      { key: "size",     label: "O'lchami (sm)",       type: "text",   placeholder: "masalan: 92, 104, 116..." },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Qizil, Ko'k, Yashil" },
      { key: "material", label: "Matosi",              type: "select", options: ["Paxta (100%)", "Fleece", "Poliester", "Jersey"] },
      { key: "gender",   label: "Jinsi",               type: "select", options: ["O'g'il bola", "Qiz bola", "Universal"] },
    ],
  },
  {
    names: ["Sport kiyimlari"], emoji: "🏋️",
    fields: [
      { key: "type",      label: "Kiyim turi",         type: "select", options: ["Sport shim", "Sport futbolka", "Sport kurtka", "Sport to'plam", "Yoga kiyimi", "Suzish kiyimi"] },
      { key: "size",      label: "O'lchami",           type: "select", options: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
      { key: "color",     label: "Rangi",              type: "text",   placeholder: "Qora, Ko'k, Yashil, Qizil" },
      { key: "material",  label: "Matosi",             type: "select", options: ["Dryfit (Poliester)", "Paxta", "Elastan mix", "Nylon", "Lycra"] },
      { key: "sportType", label: "Sport turi",         type: "select", options: ["Fitnes / Sport zali", "Yugurish", "Futbol", "Basketbol", "Tennis", "Yoga", "Universal"] },
      { key: "gender",    label: "Jinsi",              type: "select", options: ["Erkaklar", "Ayollar", "Universal"] },
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Adidas, Nike, Puma, Under Armour" },
    ],
  },
  {
    names: ["Ichki kiyim"], emoji: "🩱",
    fields: [
      { key: "type",      label: "Tur",                type: "select", options: ["Kalson", "Ko'ylakcha", "Jillik / termoichki", "Sutyen", "Yubka ichki", "Kolgramka", "Pijama"] },
      { key: "size",      label: "O'lchami",           type: "select", options: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
      { key: "color",     label: "Rangi",              type: "text",   placeholder: "Oq, Qora, Kulrang, Ko'k" },
      { key: "material",  label: "Matosi",             type: "select", options: ["Paxta", "Modalni", "Bambuk", "Poliester", "Termomaterial"] },
      { key: "gender",    label: "Jinsi",              type: "select", options: ["Erkaklar", "Ayollar", "Bolalar"] },
      { key: "packCount", label: "To'plam soni",       type: "select", options: ["1 dona", "2 dona", "3 dona", "5 dona"] },
    ],
  },
  // ── POYABZAL ─────────────────────────────────────────────────────────────────
  {
    names: ["Erkaklar poyabzali"], emoji: "👞",
    fields: [
      { key: "type",     label: "Tur",                 type: "select", options: ["Tufli (klassik)", "Botinki", "Krossovki", "Loafer", "Sandal", "Boot (qo'njli)", "Mokassin"] },
      { key: "size",     label: "O'lchami (EU)",       type: "select", options: ["39", "40", "41", "42", "43", "44", "45", "46", "47"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Qora, Jigarrang, Oq" },
      { key: "material", label: "Materiali",           type: "select", options: ["Tabiiy charm", "Ekologik charm", "Zamsha", "Tekstil", "Mesh (to'r)", "Kombinatsiya"] },
      { key: "season",   label: "Mavsumi",             type: "select", options: ["Bahor-Kuz", "Yoz (yengil)", "Qish (issiq)", "Universal"] },
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "Adidas, Nike, Clarks, Ecco" },
      { key: "sole",     label: "Tagkavar",            type: "select", options: ["Rezina", "Poliuretan (PU)", "TPR", "Charm", "EVA"] },
    ],
  },
  {
    names: ["Ayollar poyabzali"], emoji: "👠",
    fields: [
      { key: "type",       label: "Tur",               type: "select", options: ["Tufli (klassik)", "Krossovki", "Baletka", "Sandal", "Boot", "Botilyon", "Sabo", "Slippers"] },
      { key: "size",       label: "O'lchami (EU)",     type: "select", options: ["35", "36", "37", "38", "39", "40", "41", "42"] },
      { key: "color",      label: "Rangi",             type: "text",   placeholder: "Qora, Qizil, Pushti, Oq" },
      { key: "material",   label: "Materiali",         type: "select", options: ["Tabiiy charm", "Ekologik charm", "Zamsha", "Tekstil", "Kombinatsiya"] },
      { key: "heelHeight", label: "Poshnasi balandligi", type: "select", options: ["Tekis (0-2 sm)", "Kichik (2-4 sm)", "O'rta (4-7 sm)", "Baland (7+ sm)", "Platforma"] },
      { key: "season",     label: "Mavsumi",           type: "select", options: ["Bahor-Kuz", "Yoz", "Qish", "Universal"] },
      { key: "brend",      label: "Brend",             type: "text",   placeholder: "Zara, H&M, Steve Madden, Ecco" },
    ],
  },
  {
    names: ["Bolalar poyabzali"], emoji: "👟",
    fields: [
      { key: "type",     label: "Tur",                 type: "select", options: ["Krossovki", "Sandal", "Boshmoq", "Botinki", "Boot", "Slippers"] },
      { key: "size",     label: "O'lchami (EU)",       type: "select", options: ["20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Ko'k, Qizil, Pushti, Yashil" },
      { key: "material", label: "Materiali",           type: "select", options: ["Tekstil", "Ekologik charm", "Mesh (to'r)", "Rezina", "Kombinatsiya"] },
      { key: "age",      label: "Yoshi (yil)",         type: "select", options: ["0-1 yosh", "1-3 yosh", "3-6 yosh", "6-9 yosh", "9-12 yosh", "12+ yosh"] },
      { key: "gender",   label: "Jinsi",               type: "select", options: ["O'g'il bola", "Qiz bola", "Universal"] },
      { key: "closure",  label: "Mahkamlash",          type: "select", options: ["Ip bilan", "Velcro (lipuchka)", "Fermuarli", "Elastik"] },
    ],
  },
  {
    names: ["Sport poyabzali"], emoji: "🏃",
    fields: [
      { key: "type",     label: "Tur",                 type: "select", options: ["Yugurish uchun", "Fitnes / Sport zali", "Futbol bosmachi", "Basketbol", "Tennis", "Yurish"] },
      { key: "size",     label: "O'lchami (EU)",       type: "select", options: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Qora, Oq, Ko'k, Qizil" },
      { key: "material", label: "Materiali",           type: "select", options: ["Mesh (to'r)", "Tekstil", "Ekologik charm", "Kombinatsiya"] },
      { key: "sole",     label: "Tagkavar",            type: "select", options: ["Rezina (outdoor)", "Gum (indoor)", "Studs (futbol)", "Boshqa"] },
      { key: "gender",   label: "Jinsi",               type: "select", options: ["Erkaklar", "Ayollar", "Universal"] },
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "Nike, Adidas, Puma, Asics, New Balance" },
    ],
  },
  // ── GO'ZALLIK VA PARVARISH ────────────────────────────────────────────────────
  {
    names: ["Parfyumeriya"], emoji: "🌸",
    fields: [
      { key: "brend",       label: "Brend",            type: "text",   placeholder: "Hugo Boss, Chanel, Dior, Lacoste" },
      { key: "type",        label: "Tur",              type: "select", options: ["Parfyum (EDP)", "Tualetlik suv (EDT)", "Cologne (EDC)", "Dezodorant", "Body mist", "Roll-on parfyum"] },
      { key: "volume",      label: "Hajmi",            type: "select", options: ["30 ml", "50 ml", "75 ml", "100 ml", "125 ml", "150 ml", "200 ml"] },
      { key: "gender",      label: "Jins",             type: "select", options: ["Erkaklar uchun", "Ayollar uchun", "Uniseks"] },
      { key: "scentFamily", label: "Hid oilasi",       type: "select", options: ["Gulsiz (floral)", "Yog'ochli (woody)", "O'tkir (oriental)", "Yangi (fresh/aqua)", "Mevali (fruity)", "Spicy"] },
      { key: "season",      label: "Mavsum",           type: "select", options: ["Bahor-Yoz", "Kuz-Qish", "Universal"] },
    ],
  },
  {
    names: ["Makiyaj"], emoji: "💄",
    fields: [
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "L'Oreal, Maybelline, MAC, NYX" },
      { key: "type",     label: "Tur",                 type: "select", options: ["Lablar (pomada)", "Ko'z (tush/soya)", "Yuzga asos (foundation)", "Pudra", "Blush", "Highlighter", "Qosh bo'yog'i", "Mascara", "Bronzer", "Primer", "Kontur"] },
      { key: "shade",    label: "Rang / Ton",          type: "text",   placeholder: "masalan: Nude, Red, Coral, 01" },
      { key: "spf",      label: "SPF himoya",          type: "select", options: ["Yo'q", "SPF 15", "SPF 20", "SPF 30", "SPF 50+"] },
      { key: "coverage", label: "Qoplamliligi",        type: "select", options: ["Yengil (sheer)", "O'rtacha (medium)", "To'liq (full coverage)"] },
      { key: "skinType", label: "Teri turi",           type: "select", options: ["Barcha terlar", "Yog'li teri", "Quruq teri", "Kombinatsiya"] },
    ],
  },
  {
    names: ["Soch mahsulotlari"], emoji: "💇",
    fields: [
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "Pantene, Garnier, Schwarzkopf, Loreal" },
      { key: "type",     label: "Tur",                 type: "select", options: ["Shampun", "Konditsioner", "Soch maskasi", "Soch yog'i", "Styling gel", "Lak", "Musse", "Soch bo'yog'i", "Termal himoya"] },
      { key: "volume",   label: "Hajmi",               type: "select", options: ["100 ml", "150 ml", "200 ml", "250 ml", "300 ml", "400 ml", "500 ml", "1 litr"] },
      { key: "hairType", label: "Soch turi",           type: "select", options: ["Barcha sochlar", "Quruq soch", "Yog'li soch", "Rangdor soch", "Shikastlangan soch", "Burmali soch"] },
    ],
  },
  {
    names: ["Teri parvarishi"], emoji: "🧴",
    fields: [
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "CeraVe, Nivea, Garnier, The Ordinary" },
      { key: "type",     label: "Tur",                 type: "select", options: ["Yuz kremi", "Tana losyoni", "Teri tozalash", "Tonik", "Serum", "Ko'z atrofi kremi", "Quyosh himoya (SPF)", "Yuz niqobi", "Qo'l kremi", "Lip balm"] },
      { key: "volume",   label: "Hajmi",               type: "select", options: ["30 ml", "50 ml", "75 ml", "100 ml", "150 ml", "200 ml", "250 ml"] },
      { key: "skinType", label: "Teri turi",           type: "select", options: ["Barcha terlar", "Quruq teri", "Yog'li teri", "Kombinatsiya", "Sezgir teri"] },
      { key: "concern",  label: "Maqsad",              type: "select", options: ["Namlilik", "Anti-aging", "Yorqinlashtirish", "Tinchlantirish", "Akne va toshma"] },
      { key: "spf",      label: "SPF",                 type: "select", options: ["Yo'q", "SPF 15", "SPF 30", "SPF 50+"] },
    ],
  },
  {
    names: ["Erkaklar parvarishi"], emoji: "🪒",
    fields: [
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "Gillette, Nivea Men, Braun, Philips" },
      { key: "type",     label: "Tur",                 type: "select", options: ["Soqol olish kremi/geli", "Soqol yog'i", "Dush geli", "Dezodorant", "Soch mahsuloti", "Qirgich (manual)", "Elektr qirgich"] },
      { key: "volume",   label: "Hajmi",               type: "text",   placeholder: "100 ml, 200 ml, 1 dona" },
      { key: "skinType", label: "Teri turi",           type: "select", options: ["Normal", "Quruq", "Yog'li", "Sezgir"] },
    ],
  },
  // ── AVTOTOVARLAR ─────────────────────────────────────────────────────────────
  {
    names: ["Avto aksessuarlar"], emoji: "🔧",
    fields: [
      { key: "type",     label: "Aksessuar turi",      type: "select", options: ["Avto gilamchalar", "Avto qoplamalar (chehol)", "Boshqaruv qoplami", "Sun vizor", "Avto parfyum", "Avto kamera", "Parking sensor", "GPS navigatsiya", "Signalizatsiya", "Boshqa"] },
      { key: "compat",   label: "Moslik (mashina turi)", type: "text", placeholder: "masalan: Chevrolet Cobalt, Nexia, Universal" },
      { key: "material", label: "Materiali",           type: "select", options: ["Tabiiy charm", "Ekologik charm", "Plastik", "Rezina", "Tekstil", "Alyuminiy"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Qora, Kulrang, Jigarrang" },
    ],
  },
  {
    names: ["Moy va suyuqliklar"], emoji: "🛢️",
    fields: [
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Castrol, Mobil, Shell, Lukoil, ZIC" },
      { key: "type",      label: "Tur",                type: "select", options: ["Dvigatel moyi", "Transmissiya moyi", "Anti-friz (tosol)", "Tormoz suyuqligi", "Gidravlik suyuqlik", "Veter oynasi suyuqligi"] },
      { key: "volume",    label: "Hajmi",              type: "select", options: ["500 ml", "1 litr", "2 litr", "3 litr", "4 litr", "5 litr", "10 litr", "20 litr"] },
      { key: "viscosity", label: "Viskozitet (SAE)",   type: "select", options: ["0W-20", "5W-30", "5W-40", "10W-30", "10W-40", "15W-40", "20W-50", "75W-90"] },
      { key: "oilType",   label: "Moy turi",           type: "select", options: ["Sintetik (to'liq)", "Yarim sintetik", "Mineral"] },
    ],
  },
  {
    names: ["Shinalar va disklar"], emoji: "🔩",
    fields: [
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Michelin, Bridgestone, Pirelli, Continental" },
      { key: "type",      label: "Tur",                type: "select", options: ["Shina (tyre)", "Disk (rim)", "Disk + Shina to'plam"] },
      { key: "size",      label: "O'lchami",           type: "select", options: ["R13", "R14", "R15", "R16", "R17", "R18", "R19", "R20", "R21"] },
      { key: "profile",   label: "Profil / Kenglik",   type: "text",   placeholder: "masalan: 205/55, 195/65, 175/70" },
      { key: "season",    label: "Mavsumi",            type: "select", options: ["Yozgi", "Qishki", "Barcha mavsum (all season)"] },
      { key: "year",      label: "Ishlab chiqqan yil", type: "text",   placeholder: "masalan: 2023, 2024" },
      { key: "condition", label: "Holati",             type: "select", options: ["Yangi", "Ishlatilgan (yaxshi)", "Ishlatilgan (o'rtacha)"] },
    ],
  },
  {
    names: ["Avto elektronika"], emoji: "📟",
    fields: [
      { key: "brend",   label: "Brend",                type: "text",   placeholder: "Viper, Pandora, Pioneer, Sony, Xiaomi" },
      { key: "type",    label: "Tur",                  type: "select", options: ["Videoregistrator (DVR)", "Signalizatsiya", "Magnitola / Avto stereo", "Orqa kamera", "PDC sensor", "USB zaryadlagich", "Avto TV", "GPS tracker"] },
      { key: "compat",  label: "Moslik",               type: "text",   placeholder: "masalan: Chevrolet Cobalt, Universal" },
      { key: "voltage", label: "Kuchlanish",           type: "select", options: ["12V", "24V", "12/24V"] },
    ],
  },
  {
    names: ["Tozalash va kimyo"], emoji: "🧹",
    fields: [
      { key: "brend",  label: "Brend",                 type: "text",   placeholder: "Turtle Wax, Meguiar's, Grass, Liqui Moly" },
      { key: "type",   label: "Tur",                   type: "select", options: ["Kuzov poliroli", "Shina parvarishi", "Salon tozalagich", "Oyna tozalagich", "Avto shampun", "Konditsioner tozalagich", "Motorni tozalagich"] },
      { key: "volume", label: "Hajmi",                 type: "select", options: ["250 ml", "500 ml", "750 ml", "1 litr", "2 litr", "5 litr"] },
      { key: "form",   label: "Ko'rinishi",            type: "select", options: ["Suyuqlik", "Aerozol (spray)", "Gel", "Pasta", "Salfetkalar"] },
    ],
  },
  // ── BOLALAR TOVARLARI ─────────────────────────────────────────────────────────
  {
    names: ["O'yinchoqlar"], emoji: "🧸",
    fields: [
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "Lego, Barbie, Hot Wheels, Fisher-Price" },
      { key: "type",     label: "O'yinchoq turi",      type: "select", options: ["Konstruktor", "Yumshoq o'yinchoq", "Mashina va transport", "Qo'g'irchoq", "Boshqaruv (radio-controlled)", "Mozaika / Puzzl", "Musiqali o'yinchoq", "Interaktiv o'yinchoq"] },
      { key: "age",      label: "Yosh (yillar)",       type: "select", options: ["0-1 yosh", "1-3 yosh", "3-5 yosh", "5-7 yosh", "7-9 yosh", "9-12 yosh", "12+ yosh"] },
      { key: "material", label: "Materiali",           type: "select", options: ["Plastik", "Yog'och", "To'qima (mato)", "Rezina", "Metall", "Elektron"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Qizil, Ko'k, Yashil, Ko'p rang" },
      { key: "gender",   label: "Jinsi",               type: "select", options: ["O'g'il bolalar uchun", "Qiz bolalar uchun", "Universal"] },
      { key: "safety",   label: "Xavfsizlik sertifikati", type: "toggle" },
    ],
  },
  {
    names: ["Bolalar aravachalari"], emoji: "🍼",
    fields: [
      { key: "brend",     label: "Brend",              type: "text",   placeholder: "Chicco, Maxi-Cosi, Kinderkraft, Britax" },
      { key: "type",      label: "Tur",                type: "select", options: ["Klassik aravachamcha", "Progulochnya (sport)", "3-in-1 to'plam", "2-in-1", "Kolyaska + avtokreslo"] },
      { key: "maxAge",    label: "Yoshgacha",          type: "select", options: ["Yangi tug'ilganlardan", "3 yoshgacha", "4 yoshgacha"] },
      { key: "weight",    label: "Maksimal yuklanma",  type: "number", unit: "kg", placeholder: "15" },
      { key: "foldable",  label: "Yig'iladigan",       type: "toggle" },
      { key: "color",     label: "Rangi",              type: "text",   placeholder: "Qora, Kulrang, Qizil, Ko'k" },
      { key: "wheelType", label: "G'ildirak turi",     type: "select", options: ["Plastik", "Rezina (nafosatli)", "EVA ko'pik", "Combo"] },
    ],
  },
  {
    names: ["Bolalar mebeli"], emoji: "🛏️",
    fields: [
      { key: "type",     label: "Tur",                 type: "select", options: ["Bolalar karavoti", "Manezh", "Bolalar stuli", "Partalik stol", "Saqlash shkafi", "Beshik"] },
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "IKEA, Happy Baby, Micuna" },
      { key: "ageGroup", label: "Yosh guruh",          type: "select", options: ["0-1 yosh (go'daklar)", "1-3 yosh", "3-6 yosh", "6-10 yosh", "10+ yosh"] },
      { key: "material", label: "Materiali",           type: "select", options: ["Massiv yog'och", "LDSP", "MDF", "Metall", "Plastik", "Kombinatsiya"] },
      { key: "color",    label: "Rangi",               type: "text",   placeholder: "Oq, Yashil, Pushti, Natural yog'och" },
      { key: "size",     label: "O'lchami",            type: "text",   placeholder: "masalan: 120x60, 140x70 sm" },
      { key: "safe",     label: "Ekologik xavfsiz",    type: "toggle" },
    ],
  },
  {
    names: ["Ta'lim va rivojlanish"], emoji: "📚",
    fields: [
      { key: "brend",    label: "Brend",               type: "text",   placeholder: "Lego Education, Leapfrog, Vtech" },
      { key: "type",     label: "Tur",                 type: "select", options: ["Konstruktor (STEM)", "Rasm chizish to'plami", "Musiqiy asbob (bolalar)", "Logical o'yin / Boshqotin", "Bolalar kitobi", "Interaktiv plakat/ABC", "Matematik o'yinlar", "Ilmiy tajriba to'plami"] },
      { key: "ageGroup", label: "Yosh (yil)",          type: "select", options: ["0-1 yosh", "1-3 yosh", "3-5 yosh", "5-7 yosh", "7-10 yosh", "10-12 yosh", "12+ yosh"] },
      { key: "lang",     label: "Tili",                type: "select", options: ["O'zbek", "Rus", "Ingliz", "O'zbek + Rus", "O'zbek + Ingliz", "Ko'p til"] },
      { key: "subject",  label: "Yo'nalish",           type: "select", options: ["Matematika", "Til va savodxonlik", "Tabiat / Biologiya", "Texnologiya", "Ijodiy san'at", "Universal"] },
    ],
  },
  {
    names: ["Bolalar oziq-ovqati"], emoji: "🍼",
    fields: [
      { key: "brend",   label: "Brend",                type: "text",   placeholder: "Gerber, Nutrilon, Heinz, Nestle, Humana" },
      { key: "type",    label: "Tur",                  type: "select", options: ["Bolalar formulasi / sut", "Pyure (meva, sabzavot)", "Kasha", "Bolalar pechenye", "Ichimlik / shira", "Snack"] },
      { key: "minAge",  label: "Minimal yosh",         type: "select", options: ["0+ oy", "4+ oy", "6+ oy", "8+ oy", "10+ oy", "12+ oy (1 yosh)", "18+ oy", "2+ yosh", "3+ yosh"] },
      { key: "weight",  label: "Og'irligi / Hajmi",    type: "text",   placeholder: "masalan: 400 g, 500 ml, 250 g" },
      { key: "allergen", label: "Asosiy allergeni",    type: "select", options: ["Yo'q (allergen free)", "Sut mahsuloti", "Gluten", "Meva", "Yer yong'oq"] },
      { key: "organic", label: "Organik / BIO",        type: "toggle" },
    ],
  },
  // ── Aksessuarlar ──────────────────────────────────────────────
  {
    names: ["Sumkalar"], emoji: "👜",
    fields: [
      { key: "brend",    label: "Brend",          type: "text",   placeholder: "Gucci, Zara, H&M, Adidas, mahalliy brend" },
      { key: "type",     label: "Tur",            type: "select", options: ["Elka sumkasi (handbag)", "Yelka sumkasi (shoulder bag)", "Ryukzak", "Portfel", "Bel sumkasi (belt bag)", "Krossbodi sumka", "Kechki sumka (clutch)", "Sport sumkasi", "Sayohat sumkasi"] },
      { key: "material", label: "Material",       type: "select", options: ["Charm", "Sun'iy charm (PU)", "Nylon", "Kanvas", "Poliester", "Zamsha", "Kombinatsiya"] },
      { key: "color",    label: "Rang",           type: "text",   placeholder: "masalan: qora, jigarrang, bej" },
      { key: "size",     label: "O'lcham (sm)",   type: "text",   placeholder: "masalan: 30x20x10 sm" },
      { key: "gender",   label: "Jins",           type: "select", options: ["Ayollar", "Erkaklar", "Unisex", "Bolalar"] },
      { key: "closure",  label: "Yopilish turi",  type: "select", options: ["Fermuar", "Tugma", "Magnit tokcha", "Tovoqcha (buckle)", "Ochiq"] },
    ],
  },
  {
    names: ["Hamyonlar"], emoji: "👛",
    fields: [
      { key: "brend",     label: "Brend",             type: "text",   placeholder: "Louis Vuitton, Zara, H&M, mahalliy brend" },
      { key: "type",      label: "Tur",               type: "select", options: ["Bifold hamyon", "Trifold hamyon", "Kartochkalar egasi (card holder)", "Ko'p bo'limli hamyon", "Telefon-hamyon (phone wallet)", "Bel hamyon"] },
      { key: "material",  label: "Material",          type: "select", options: ["Charm", "Sun'iy charm (PU)", "Nylon", "Kanvas", "Metall", "Zamsha"] },
      { key: "color",     label: "Rang",              type: "text",   placeholder: "masalan: qora, jigarrang, qo'ng'ir" },
      { key: "gender",    label: "Jins",              type: "select", options: ["Erkaklar", "Ayollar", "Unisex"] },
      { key: "cardSlots", label: "Karta uyalari",     type: "select", options: ["1-4 ta", "5-8 ta", "9-12 ta", "12+ ta"] },
    ],
  },
  {
    names: ["Zargarlik va bijuteriya"], emoji: "💍",
    fields: [
      { key: "brend",    label: "Brend",           type: "text",   placeholder: "masalan: Pandora, Sokolov, mahalliy zargar" },
      { key: "type",     label: "Tur",             type: "select", options: ["Uzuk", "Bilakuzuk (braslet)", "Marjon / gavhar / zanjir", "Zirg'oq / sirg'a", "Broş", "Ko'krak zanjiri (necklace)", "To'plam (komplekt)", "Engil zargarlik (bijuteriya)"] },
      { key: "material", label: "Material",        type: "select", options: ["Oltin 585 (14K)", "Oltin 750 (18K)", "Kumush 925", "Platina", "Zanglamaydigan po'lat (316L)", "Mis asosli bijuteriya", "Kristal / shisha", "Kombinatsiya"] },
      { key: "stone",    label: "Tosh",            type: "select", options: ["Yo'q (tashtoshsiz)", "Olmos", "Brilyant", "Zumrad (emerald)", "Yoqut (ruby)", "Ko'k tosh (sapfir)", "Yarim qimmatbaho tosh", "Sintetik / CZ tosh", "Kristal"] },
      { key: "color",    label: "Rang / Ton",      type: "text",   placeholder: "masalan: sariq oltin, oq oltin, kumush" },
      { key: "size",     label: "O'lcham",         type: "text",   placeholder: "masalan: 17 mm (uzuk), 18 sm (bilakuzuk)" },
      { key: "gender",   label: "Jins",            type: "select", options: ["Ayollar", "Erkaklar", "Unisex", "Bolalar"] },
    ],
  },
  {
    names: ["Soatlar"], emoji: "⌚",
    fields: [
      { key: "brend",         label: "Brend",                  type: "text",   placeholder: "Casio, Orient, Tissot, Samsung, Apple, Citizen" },
      { key: "type",          label: "Tur",                    type: "select", options: ["Qo'l soati (analog)", "Qo'l soati (raqamli)", "Smart soat", "Sport soat", "Klassik soat", "Bolalar soati", "Cho'ntak soati"] },
      { key: "mechanism",     label: "Mexanizm",               type: "select", options: ["Kvarts (batareya)", "Mexanik (qo'lda o'rash)", "Avtomatik (o'z-o'zidan o'rash)", "Solar (quyosh energiyasi)", "Smart / Hybrid"] },
      { key: "caseMaterial",  label: "Qo'ng'iroq materiali",   type: "select", options: ["Zanglamaydigan po'lat", "Titan", "Plastik / polikarbonat", "Keramika", "Oltin qoplama", "Alyuminiy", "Kombinatsiya"] },
      { key: "strapMaterial", label: "Qayish materiali",       type: "select", options: ["Charm", "Metall zanjir (bracelet)", "Silikon", "Nylon / kanvas", "Rezin", "Keramika", "Kombinatsiya"] },
      { key: "waterResist",   label: "Suv o'tkazmasligi",      type: "select", options: ["Yo'q", "3 ATM (yomg'ir / sochilish)", "5 ATM (oddiy suzish)", "10 ATM (sho'ng'ish)", "20+ ATM (professional sho'ng'ish)"] },
      { key: "color",         label: "Rang",                   type: "text",   placeholder: "masalan: qora, kumush, oltin" },
      { key: "gender",        label: "Jins",                   type: "select", options: ["Erkaklar", "Ayollar", "Unisex", "Bolalar"] },
      { key: "warranty",      label: "Kafolat",                type: "select", options: ["6 oy", "12 oy", "18 oy", "24 oy", "Kafolatsiz"] },
    ],
  },
  {
    names: ["Ko'zoynak"], emoji: "🕶️",
    fields: [
      { key: "brend",         label: "Brend",             type: "text",   placeholder: "Ray-Ban, Oakley, Gucci, Dolce, mahalliy" },
      { key: "type",          label: "Tur",               type: "select", options: ["Quyosh ko'zoynagi", "Optik ko'zoynak (minus/plus)", "Kompyuter ko'zoynagi (antiblik)", "Sport ko'zoynagi", "Bolalar ko'zoynagi", "O'qish uchun ko'zoynak"] },
      { key: "frameType",     label: "Ramka turi",        type: "select", options: ["To'liq ramka (full-rim)", "Yarim ramka (semi-rim)", "Ramsiz (rimless)", "Nozik ramka (thin-rim)"] },
      { key: "frameMaterial", label: "Ramka materiali",   type: "select", options: ["Plastik / Atsetat", "Metall", "Titan", "TR90 (elastik plastik)", "Kombinatsiya"] },
      { key: "lensMaterial",  label: "Linza materiali",   type: "select", options: ["Polimer / CR-39", "Polikarbonat", "Shisha", "Trivex", "Progressiv (ko'p fokusli)"] },
      { key: "color",         label: "Ramka rangi",       type: "text",   placeholder: "masalan: qora, shaffof, qo'ng'ir" },
      { key: "gender",        label: "Jins",              type: "select", options: ["Erkaklar", "Ayollar", "Unisex", "Bolalar"] },
      { key: "uvProtection",  label: "UV himoya",         type: "toggle" },
    ],
  },
  {
    names: ["Kamarlar"], emoji: "🪢",
    fields: [
      { key: "brend",      label: "Brend",         type: "text",   placeholder: "masalan: Gucci, H&M, Zara, mahalliy" },
      { key: "type",       label: "Tur",           type: "select", options: ["Klassik charm kamar", "Jins kamar", "Keng kamar (fashion belt)", "Sport kamar", "Taktik / harbiy kamar"] },
      { key: "material",   label: "Material",      type: "select", options: ["Charm", "Sun'iy charm (PU)", "Kanvas", "Nylon", "Rezin / elastik", "Kombinatsiya"] },
      { key: "width",      label: "Kenglik",       type: "select", options: ["2 sm", "3 sm", "3.5 sm", "4 sm", "5 sm", "6+ sm"] },
      { key: "buckle",     label: "Tokcha turi",   type: "select", options: ["Pin tokcha (klassik)", "Plastinka tokcha (plate)", "Avtomatik tokcha", "Taktik tokcha", "Teshiksiz (ratchet)"] },
      { key: "color",      label: "Rang",          type: "text",   placeholder: "masalan: qora, jigarrang, bej" },
      { key: "gender",     label: "Jins",          type: "select", options: ["Erkaklar", "Ayollar", "Unisex"] },
      { key: "adjustable", label: "Regulyatsiya",  type: "toggle" },
    ],
  },
  {
    names: ["Shlyapalar va qalpoqlar"], emoji: "🧢",
    fields: [
      { key: "brend",      label: "Brend",         type: "text",   placeholder: "New Era, Nike, Adidas, mahalliy" },
      { key: "type",       label: "Tur",           type: "select", options: ["Baseball kepka", "Snapback", "Dad hat (low-profile)", "Qishki shapka (beanie)", "Panama shlyapa", "Fedora shlyapa", "Yozgi saman shlyapa", "Beret", "Bolalar kepkasi"] },
      { key: "material",   label: "Material",      type: "select", options: ["Paxta", "Akril", "Yun / kashmir", "Polyester", "Charm", "Kanvas / denim", "Nylon"] },
      { key: "size",       label: "O'lcham",       type: "text",   placeholder: "masalan: S/M, L/XL yoki 56-58 sm" },
      { key: "season",     label: "Mavsum",        type: "select", options: ["Yozgi", "Qishki", "Bahori-kuzgi", "Barcha fasllar"] },
      { key: "color",      label: "Rang",          type: "text",   placeholder: "masalan: qora, oq, ko'k" },
      { key: "gender",     label: "Jins",          type: "select", options: ["Erkaklar", "Ayollar", "Unisex", "Bolalar"] },
      { key: "adjustable", label: "Regulyatsiya",  type: "toggle" },
    ],
  },
  {
    names: ["Telefon aksessuarlari"], emoji: "📱",
    fields: [
      { key: "type",          label: "Tur",              type: "select", options: ["Telefon chexoli / qopqoq", "Ekran himoyachisi (shisha / plyonka)", "Zaryadlovchi / kabel", "Simsiz zaryadlovchi (wireless)", "Quloqchin / naushnik", "Bluetooth kalonka", "Telefon tutgich (holder / stand)", "Quvvat banki (power bank)", "Kamera linzasi (lens kit)", "Halqa / grip / popsocket"] },
      { key: "compatibility", label: "Mos model",        type: "text",   placeholder: "masalan: iPhone 15 Pro, Samsung Galaxy S24" },
      { key: "material",      label: "Material",         type: "select", options: ["Silikon", "Plastik / polikarbonat", "Charm / charm o'xshash", "Metall / alyuminiy", "Shisha (tempered glass)", "Kombinatsiya"] },
      { key: "color",         label: "Rang",             type: "text",   placeholder: "masalan: qora, shaffof, ko'k" },
      { key: "brend",         label: "Brend",            type: "text",   placeholder: "Apple, Samsung, Baseus, Ugreen, mahalliy" },
      { key: "warranty",      label: "Kafolat",          type: "select", options: ["6 oy", "12 oy", "Kafolatsiz"] },
    ],
  },

  // ══════════════════ YANGI QO'SHILGAN KATEGORIYALAR ══════════════════

  // ── MEBEL YANGI SUBLAR ────────────────────────────────────────────────────────
  {
    names: ["Buyurtma mebel"], emoji: "🛠️",
    fields: [
      { key: "mebelType",  label: "Mebel turi",           type: "select", options: ["Shkaf (kupe/klassik)","Oshxona garnitur","Kiyinish xonasi","Bola xonasi","Yotoqxona garnitur","Divan","Stol","Javon","Boshqa"] },
      { key: "corpusMat",  label: "Korpus materiali",     type: "select", options: KORPUS_OPTS },
      { key: "facadeMat",  label: "Fasad materiali",      type: "select", options: FASAD_OPTS },
      { key: "color",      label: "Rangi",                type: "text",   placeholder: "masalan: Oq, Wenge, Kulrang" },
      { key: "width",      label: "Eni",                  type: "number", unit: "sm",  placeholder: "masalan: 200" },
      { key: "height",     label: "Balandligi",           type: "number", unit: "sm",  placeholder: "masalan: 240" },
      { key: "depth",      label: "Chuqurligi",           type: "number", unit: "sm",  placeholder: "masalan: 60" },
      { key: "design",     label: "3D dizayn taqdim etiladi", type: "toggle" },
      { key: "install",    label: "O'rnatish xizmati bilan",  type: "toggle" },
      { key: "warranty",   label: "Kafolat",              type: "select", options: ["6 oy","1 yil","2 yil","3 yil"] },
    ],
  },
  {
    names: ["Mebel furniturasi"], emoji: "🔩",
    fields: [
      { key: "hardwareType", label: "Furnitura turi",     type: "select", options: ["Ruchka (tutqich)","Petlya (loop)","Zamok","Kanallar (rol)","Yulduzcha (tayanch)","To'siq (amortizator)","Mebel oyog'i","Magnit tutgich","Slayder tizim","Vida va qoziqlar"] },
      { key: "material",   label: "Materiali",            type: "select", options: ["Xrom po'lat","Qora po'lat","Bronza","Oltin","Plastik (ABS)","Nikel","Mis","Alyuminiy"] },
      { key: "color",      label: "Rangi",                type: "text",   placeholder: "masalan: Xrom, Matli qora, Bronza" },
      { key: "brand",      label: "Brend",                type: "text",   placeholder: "masalan: Blum, Hettich, Hafele, Grass" },
      { key: "packCount",  label: "To'plamdagi dona",     type: "select", options: ["1","2","4","6","8","10","12","20+"] },
      { key: "compat",     label: "Mos mebel materiali",  type: "text",   placeholder: "masalan: LDSP, MDF, Massiv yog'och" },
    ],
  },
  {
    names: ["Yashash xonasi"], emoji: "🛋️",
    fields: [
      { key: "setType",    label: "To'plam turi",         type: "select", options: ["Divan + kreslo to'plam","Faqat divan","Modul divan","Gostinnaya garnitur","To'liq yashash xonasi garnitur"] },
      { key: "corpusMat",  label: "Korpus materiali",     type: "select", options: KORPUS_OPTS },
      { key: "facadeMat",  label: "Qoplama / fasad",      type: "select", options: ["Haqiqiy teri","Eko-teri","Velur","Mato","Bukle","Shenil","Laminat","MDF bo'yalgan","Akrilik"] },
      { key: "color",      label: "Rangi",                type: "text",   placeholder: "masalan: Kulrang, Bej, To'q jigarrang" },
      { key: "style",      label: "Dizayn uslubi",        type: "select", options: ["Zamonaviy (modern)","Klassik","Minimalizm","Loft / Industrial","Art Deco","Skandinavcha"] },
      { key: "foldable",   label: "Yotiladigan divan",    type: "toggle" },
      { key: "storage",    label: "Qutilar bilan",        type: "toggle" },
      { key: "assembly",   label: "Yig'ilgan holda yetkazish", type: "toggle" },
    ],
  },
  {
    names: ["Koridor va dahliz"], emoji: "🚪",
    fields: [
      { key: "hallType",   label: "Mebel turi",           type: "select", options: ["Tayanchli shkaf (veshank)","Poyabzal shkafi","Ko'zgu + shelf","Devorga osish tizimi","Polkali stend","To'liq garnitur (kombo)"] },
      { key: "corpusMat",  label: "Korpus materiali",     type: "select", options: KORPUS_OPTS },
      { key: "color",      label: "Rangi",                type: "text",   placeholder: "masalan: Oq, Wenge, Kulrang" },
      { key: "width",      label: "Eni",                  type: "number", unit: "sm",  placeholder: "masalan: 100" },
      { key: "height",     label: "Balandligi",           type: "number", unit: "sm",  placeholder: "masalan: 200" },
      { key: "mirror",     label: "Ko'zgu bilan",         type: "toggle" },
      { key: "shoeRack",   label: "Poyabzal rafi bilan",  type: "toggle" },
      { key: "assembly",   label: "Yig'ilgan holda yetkazish", type: "toggle" },
    ],
  },
  {
    names: ["Oynalar va zerkalo"], emoji: "🪞",
    fields: [
      { key: "mirrorType", label: "Ko'zgu turi",          type: "select", options: ["Devorga osuvchi","Erkin turuvchi (pol ko'zgusi)","Hammom ko'zgusi","Makiyaj ko'zgusi","Eshik ko'zgusi","Dekorativ ramkali"] },
      { key: "shape",      label: "Shakli",               type: "select", options: ["To'rtburchak","Oval","Doira","Noodatiy (art)","To'liq bo'y"] },
      { key: "frameMat",   label: "Ramka materiali",      type: "select", options: ["Ramsiz","Metall (xrom)","Metall (qora)","Bronza / Oltin","Yog'och massiv","MDF bo'yalgan","Plastik","Alyuminiy"] },
      { key: "width",      label: "Eni",                  type: "number", unit: "sm",  placeholder: "masalan: 60" },
      { key: "height",     label: "Balandligi",           type: "number", unit: "sm",  placeholder: "masalan: 80" },
      { key: "color",      label: "Ramka rangi",          type: "text",   placeholder: "masalan: Qora, Bronza, Oq" },
      { key: "backlight",  label: "LED yoritish bilan",   type: "toggle" },
      { key: "antiFog",    label: "Bug'lanmaydigan (anti-fog)", type: "toggle" },
      { key: "wallMount",  label: "O'rnatish moslamalari bilan", type: "toggle" },
    ],
  },

  // ── UY-RO'ZG'OR YANGI SUBLAR ─────────────────────────────────────────────────
  {
    names: ["To'qimachilik"], emoji: "🧶",
    fields: [
      { key: "itemType",   label: "Mahsulot turi",        type: "select", options: ["Ip (yarn)","Gazlama (mato)","Tikuv matolari","To'qimachilik asboblari","Kashtachilik to'plami","Dastgoh aksessuarlari"] },
      { key: "material",   label: "Materiali",            type: "select", options: ["Paxta","Jun (wool)","Akril","Poliester","Ipak","Bambuk","Zig'ir (linen)","Mikrofibra","Naylon","Gibrid"] },
      { key: "color",      label: "Rangi",                type: "text",   placeholder: "masalan: Qizil, Ko'k, Aralash ranglar" },
      { key: "weight",     label: "Og'irligi / Uzunligi", type: "text",   placeholder: "masalan: 100 g / 200 m" },
      { key: "thickness",  label: "Ip yo'g'onligi",       type: "select", options: ["Juda nozik (fingering)","Nozik (sock)","O'rtacha (DK)","Yo'g'on (worsted)","Juda yo'g'on (bulky)","Super yo'g'on (super bulky)"] },
      { key: "brand",      label: "Brend",                type: "text",   placeholder: "masalan: Drops, Alize, Gazzal, Kartopu" },
    ],
  },
  {
    names: ["Xo'jalik buyumlari"], emoji: "🏠",
    fields: [
      { key: "itemType",   label: "Buyum turi",           type: "select", options: ["Chelak","Plastik qozon","Idish qopqog'i","Mop to'plami","Supurgi + dastaki","Lattalar","Qo'lqop (uy ishi)","Ko'z qopchiq","Hammom gilami","Rezina gilam","Boshqa"] },
      { key: "material",   label: "Materiali",            type: "select", options: ["Plastik (PP)","Metall","Paslanmaz po'lat","Alyuminiy","Rezina","Mato","Bambuk"] },
      { key: "color",      label: "Rangi",                type: "text",   placeholder: "masalan: Oq, Kulrang, Ko'k" },
      { key: "size",       label: "O'lchami / Hajmi",     type: "text",   placeholder: "masalan: 10 litr, 30×20 sm" },
      { key: "packCount",  label: "To'plamdagi dona",     type: "select", options: ["1 dona","2 dona","3 dona","5 dona","10 dona","To'plam"] },
    ],
  },

  // ── MAISHIY TEXNIKA YANGI SUBLAR ─────────────────────────────────────────────
  {
    names: ["Tikuv mashinalari"], emoji: "🧵",
    fields: [
      { key: "brand",       label: "Brend",               type: "text",   placeholder: "masalan: Singer, Brother, Janome, Juki" },
      { key: "machineType", label: "Mashina turi",        type: "select", options: ["Mexanik","Elektr (avtomatik)","Kompyuter (raqamli)","Overlock","Ko'p funksiyali (kombinatsiya)"] },
      { key: "stitchCount", label: "Tikuv turlari soni",  type: "select", options: ["10–20","21–50","51–100","101–200","200+"] },
      { key: "speed",       label: "Tezligi",             type: "number", unit: "tikiş/min", placeholder: "masalan: 800" },
      { key: "motorPow",    label: "Motor quvvati",       type: "number", unit: "W", placeholder: "masalan: 100" },
      { key: "freeArm",     label: "Free-arm funksiyasi", type: "toggle" },
      { key: "autoThread",  label: "Avtomatik ip tortish", type: "toggle" },
      { key: "warranty",    label: "Kafolat",             type: "select", options: ["1 yil","2 yil","3 yil","5 yil"] },
    ],
  },
  {
    names: ["Dazmollar va bug'lagichlar"], emoji: "👔",
    fields: [
      { key: "brand",       label: "Brend",               type: "text",   placeholder: "masalan: Philips, Tefal, Bosch, Rowenta" },
      { key: "ironType",    label: "Qurilma turi",        type: "select", options: ["Elektr dazmol","Bug' dazmol (generatorli)","Vertikal bug'lagich","Ko'chma bug'lagich","Avtomatik (smart)"] },
      { key: "power",       label: "Quvvati",             type: "number", unit: "W", placeholder: "masalan: 2400" },
      { key: "pressure",    label: "Bug' bosimi",         type: "text",   placeholder: "masalan: 5.5 bar, 6 bar" },
      { key: "tankVol",     label: "Suv idishi hajmi",    type: "text",   placeholder: "masalan: 300 ml, 1.5 litr" },
      { key: "soleMat",     label: "Dazmol tagligi",      type: "select", options: ["Keramika","Titan","Paslanmaz po'lat","Durilium","Eloxal alyuminiy"] },
      { key: "tempCtrl",    label: "Harorat rostlash",    type: "toggle" },
      { key: "selfClean",   label: "Tozalanish funksiyasi", type: "toggle" },
      { key: "warranty",    label: "Kafolat",             type: "select", options: ["1 yil","2 yil","3 yil"] },
    ],
  },
  {
    names: ["Go'zallik uchun texnika"], emoji: "💅",
    fields: [
      { key: "brand",       label: "Brend",               type: "text",   placeholder: "masalan: Philips, Braun, Dyson, Remington" },
      { key: "beautyType",  label: "Qurilma turi",        type: "select", options: ["Soch quritgich (fen)","Soch tekislagich (planka)","Lokonga (qisqich)","Elektr qirgich (ayol)","Yuz tozalagich","Yuz massajori","Tikuvchi (epilator)","Tırnoq quritgich (UV/LED)","Boshqa"] },
      { key: "power",       label: "Quvvati",             type: "number", unit: "W", placeholder: "masalan: 2000" },
      { key: "voltage",     label: "Kuchlanish",          type: "select", options: ["220V","Dual (110/220V)","USB zaryadka"] },
      { key: "heatSetting", label: "Harorat sozlamalari", type: "select", options: ["1 daraja","2 daraja","3 daraja","5+ daraja","Raqamli (LCD)"] },
      { key: "ionizer",     label: "Ionizator (soch parvarishi)", type: "toggle" },
      { key: "wireless",    label: "Simsiz (akkumulyatorli)", type: "toggle" },
      { key: "warranty",    label: "Kafolat",             type: "select", options: ["1 yil","2 yil","3 yil"] },
    ],
  },

  // ── QURILISH VA TA'MIRLASH YANGI SUBLAR ──────────────────────────────────────
  {
    names: ["Elektr asboblari"], emoji: "🔌",
    fields: [
      { key: "brand",       label: "Brend",               type: "text",   placeholder: "masalan: Bosch, Makita, DeWalt, Hilti" },
      { key: "toolType",    label: "Asbob turi",          type: "select", options: ["Burg'ulama (drel)","Perforator","Bolg'a sima (shlifovka)","Elektr arra (tsirkulyar)","Jigsaw (lob-arra)","Burchak toshlagich (UShM)","Kompressor","Lehimlagich","Elektr planer","Multi-tool","Boshqa"] },
      { key: "power",       label: "Quvvati",             type: "number", unit: "W", placeholder: "masalan: 1200" },
      { key: "voltage",     label: "Kuchlanish",          type: "select", options: ["12V (akkumulyator)","18V (akkumulyator)","20V (akkumulyator)","220V (setli)","Dual (akkumulyator+setli)"] },
      { key: "speed",       label: "Aylanish tezligi",    type: "text",   placeholder: "masalan: 0–3000 rpm, variable" },
      { key: "cordless",    label: "Akkumulyatorli (cordless)", type: "toggle" },
      { key: "sds",         label: "SDS qisqich (perforator)",  type: "toggle" },
      { key: "warranty",    label: "Kafolat",             type: "select", options: ["1 yil","2 yil","3 yil","5 yil"] },
    ],
  },
  {
    names: ["Gul qog'ozlar va elimlar"], emoji: "🎨",
    fields: [
      { key: "itemType",   label: "Mahsulot turi",        type: "select", options: ["Devor tapetasi (gul qog'oz)","Dekorativ plyonka","Foto tapeta","Flizelin tapeta","3D panel","Elim (kley)","Grunt (astar)","Silikon germetik","Akrilik germetik","Montaj ko'puk"] },
      { key: "material",   label: "Materiali",            type: "select", options: ["Qog'oz asosli","Vinil","Fleece (flizelin)","Foto print","3D material","Polimer ko'puk","Keramika"] },
      { key: "width",      label: "Rul eni",              type: "number", unit: "sm",  placeholder: "masalan: 53" },
      { key: "length",     label: "Uzunligi",             type: "number", unit: "m",   placeholder: "masalan: 10" },
      { key: "color",      label: "Rangi / Dizayni",      type: "text",   placeholder: "masalan: Kulrang zolot, Beton effekt, Oq" },
      { key: "washable",   label: "Yuviladigan sirt",     type: "toggle" },
    ],
  },

  // ── GO'ZALLIK VA PARVARISH YANGI SUBLAR ──────────────────────────────────────
  {
    names: ["Onalar va chaqaloqlar"], emoji: "🍼",
    fields: [
      { key: "brand",      label: "Brend",               type: "text",   placeholder: "masalan: Chicco, Avent, Medela, Johnson's" },
      { key: "itemType",   label: "Mahsulot turi",        type: "select", options: ["Ko'krak sog'ish asbobi","Shisha butilka","Chaqaloq so'rg'ich","Bolalar kremi","Bolalar shampuni","Bolalar yog'i","Bolalar nam sochig'i","Qorin belbog'i (bandaj)","Hamiladorlik kremi","Bolalar sovuni","Ona parvarishi to'plami"] },
      { key: "ageGroup",   label: "Yosh guruh",          type: "select", options: ["0+ (yangi tug'ilgan)","3+ oy","6+ oy","12+ oy (1 yosh)","Hamiladorlik davri","Universal"] },
      { key: "volume",     label: "Hajmi / Miqdori",     type: "text",   placeholder: "masalan: 250 ml, 100 g, 1 dona" },
      { key: "organic",    label: "Organik / BIO tarkib", type: "toggle" },
      { key: "allergenFree", label: "Gipoallergen",      type: "toggle" },
      { key: "pediatric",  label: "Pediatr tavsiyasi",   type: "toggle" },
    ],
  },
  {
    names: ["Shaxsiy gigiena"], emoji: "🧼",
    fields: [
      { key: "brand",      label: "Brend",               type: "text",   placeholder: "masalan: Colgate, Oral-B, Nivea, Dove, Rexona" },
      { key: "itemType",   label: "Mahsulot turi",        type: "select", options: ["Tish pastasi","Tish cho'tkasi","Elektr tish cho'tkasi","Og'iz chayqash suyuqligi","Dezodorant","Antibakterial sabun","Dush geli","Yuz yuvish geli","Yuz skrabi","Taroq / taroqcha","Qo'l tozalagich","Sochiq (hammom)","Gigiena paketi"] },
      { key: "gender",     label: "Jins",                type: "select", options: ["Erkaklar","Ayollar","Universal","Bolalar"] },
      { key: "volume",     label: "Hajmi",               type: "text",   placeholder: "masalan: 100 ml, 200 ml, 1 dona" },
      { key: "scent",      label: "Hidi",                type: "select", options: ["Hidsiz","Limon","Lavanda","Yashil choy","Menta","Dengiz","O'tlar aralashmasi"] },
      { key: "ecofriendly", label: "Ekologik tarkibli",  type: "toggle" },
      { key: "antibac",    label: "Antibakterial",       type: "toggle" },
    ],
  },

  // ── KITOBLAR VA KANSELYARIYA ──────────────────────────────────────────────────
  {
    names: ["Kitoblar"], emoji: "📖",
    fields: [
      { key: "genre",      label: "Janr",                type: "select", options: ["Roman / Badiiy adabiyot","Ilmiy-ommabop","O'quv qo'llanma (darslik)","Bolalar kitobi","Biznes va moliya","Tarix","Falsafa","Psixologiya","Tillar o'rganish","She'riyat","Diniy / Ma'naviy","Detektiv / Triller","Ilmiy fantastika","Biografiya","Ovqatpazlik","Boshqa"] },
      { key: "lang",       label: "Tili",                type: "select", options: ["O'zbek","Rus","Ingliz","O'zbek + Rus","O'zbek + Ingliz","Arabiy","Ko'p til"] },
      { key: "author",     label: "Muallif",             type: "text",   placeholder: "masalan: Chulpan, Abdulla Qodiriy, Osho" },
      { key: "publisher",  label: "Nashriyot",           type: "text",   placeholder: "masalan: O'qituvchi, Yangi asr avlodi" },
      { key: "year",       label: "Nashr yili",          type: "text",   placeholder: "masalan: 2023, 2024" },
      { key: "coverType",  label: "Muqova turi",         type: "select", options: ["Qattiq muqova","Yumshoq muqova","Spiral muqova","Elektron (PDF/EPUB)"] },
      { key: "pages",      label: "Sahifalar soni",      type: "number", unit: "bet",  placeholder: "masalan: 320" },
      { key: "condition",  label: "Holati",              type: "select", options: ["Yangi (muhr yopiq)","Yaxshi holat","O'rtacha holat"] },
    ],
  },
  {
    names: ["Kanselyariya tovarlari"], emoji: "✏️",
    fields: [
      { key: "itemType",   label: "Mahsulot turi",        type: "select", options: ["Ruchka (ballpoint/gel)","Qalam (oddiy/ranga)","Marker / Flomaster","Daftar","Bloknot / Planner","Papka va fayl","Qisgich (skotch/stepler)","Qaychi","Ko'chirma qog'ozi","Maket pichog'i","O'chirg'ich","Linejka","Kompas va burchaklar","Geometriya to'plami","Renglar to'plami","Kley / Elim","Boshqa"] },
      { key: "brand",      label: "Brend",               type: "text",   placeholder: "masalan: Deli, Faber-Castell, Pilot, BIC" },
      { key: "color",      label: "Rangi",               type: "text",   placeholder: "masalan: Ko'k, Qizil, Qora, Aralash" },
      { key: "packCount",  label: "To'plamdagi dona",     type: "select", options: ["1 dona","6 dona","10 dona","12 dona","20 dona","50 dona","100 dona","To'plam (set)"] },
      { key: "size",       label: "Daftar / qog'oz o'lchami", type: "select", options: ["A6 (148×105 mm)","A5 (210×148 mm)","A4 (297×210 mm)","A3 (420×297 mm)","Boshqa"] },
      { key: "forStudents", label: "O'quvchilar uchun",  type: "toggle" },
    ],
  },
];
